### ISSUE TITLE
Swipe feature doesn't work with modern navigation

### ISSUE THREAD

**Issue by imrohitkumar** [jamal2362/Styx#1]
I think the features you added like swipe left to open tabs and swipe right open bookmarks doesn't goes well with modern navigation as you know swipe left and right are assigned for back buttons in modern navigation.
So app quits when opening recent tabs or opening bookmarks.

**Comment by Slion** [comment]
I don't know what was done in Styx but with Fulguris those are disabled by default.
The relevant settings option is _Look & Feel > Locked drawers_
See: https://slions.net/resources/fulguris.10/

**Comment by jamal2362** [comment]
Hi,

This can be changed in the settings as Slion says.
I just changed the default. But that is done with a few clicks in the settings.

:)

**Comment by jamal2362** [comment]
> I think the features you added like swipe left to open tabs and swipe right open bookmarks doesn't goes well with modern navigation as you know swipe left and right are assigned for back buttons in modern navigation.
> So app quits when opening recent tabs or opening bookmarks.

Feature added in v6.8.0.
https://github.com/jamal2362/Styx/issues/3
