### ISSUE TITLE
ad blocker issue

### ISSUE THREAD

**Issue by BioBut** [jamal2362/Styx#10]
some  website use Ad blocker detection script (notification visible ) , please add specific website ad block enable/disable option  
example  
https://disableadblock.com/developers/

**Comment by jamal2362** [comment]
You can find it here.

![Screenshot_20210501-073802](https://user-images.githubusercontent.com/15986930/116772597-71e6f880-aa50-11eb-8e8c-07039b9dffb6.jpg)

![Screenshot_20210501-073837](https://user-images.githubusercontent.com/15986930/116772603-76abac80-aa50-11eb-939f-3143c91e14b4.jpg)
