### ISSUE TITLE
Add more one color scheme

### ISSUE THREAD

**Issue by ThIsLinked** [jamal2362/Styx#100]
Hi. It is not necessary, but I would like to see it. At the moment, the default schema is red. Can I make the default scheme [Royal Blue](//en.m.wikipedia.org/wiki/Royal_blue) ? His Hexadecimal value "4169e1" for light theme and "8ab4f8" for dark and black theme. And the replacement circuit will be red in the list as an additional option. Again, this is not a mandatory wish. If necessary, I can provide additional information. Thanks. (Google Translate)

**Comment by jamal2362** [comment]
Hello,
I will not change the color system for now, but it may happen in the future. 
But currently not.
