### ISSUE TITLE
Customizing download location causes Application not responding

### ISSUE THREAD

**Issue by JLFaraut** [jamal2362/Styx#104]
**Describe the bug**
Styx blocks when trying to customize download location

**To Reproduce**
1. Go to Settings
2. Click on first entry
3. Scroll down to download location
4. Try to customize, then typing a single character on my phone's keyboard blocks Styx . I can only kill the app to unlock.

**Expected behavior**
Dunno if this is just me, but it is somewhat annoying

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi 5 plus MIUI 12.5
 - OS: Android 10
 - Browser [e.g. Styx Browser]
 - Version all

**Additional context**

**Comment by jamal2362** [comment]
Hi,
Please don't be angry that I removed this function. It's bugged and it doesn't make sense to change the download location anymore.

https://github.com/jamal2362/Styx/commit/962396abc6fdb01a3347cd630666b0a4a9c972d8
