### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by ThIsLinked** [jamal2362/Styx#105]
Hi. I should have said this earlier.

1. About the file download dialog box. If you check the box, so that the next time you do not show the window, it will not be possible to disable it? Maybe you should add an analogue of this checkbox to the settings as a switch?
![1.jpg](https://user-images.githubusercontent.com/45180688/140884215-8606f965-0a1b-41e4-8542-dfb6db0c8255.jpg)

2. Translate. When you enable it, the URL changes, that is, in fact, the page is opened through the translator. Thus, it cannot be disabled - you have to open the page on a new one in order to remove the translation. Maybe when the translator is activated, the tab is duplicated - in the first original, in the second translation?  
Well, it's like a simple solution.
![2.jpg](https://user-images.githubusercontent.com/45180688/140884272-73888a8d-d1eb-469a-ae61-582f58c3c7be.jpg)

3. «Third party application linked» dialog box. It becomes obsessive. I download the file and it keeps coming to me because I have Chrome and DVGet installed. I think it's worth it to hide somehow. Or do it through the settings. You can think about it.
![3.jpg](https://user-images.githubusercontent.com/45180688/140885211-5d03e027-8fc4-4ded-8636-9fc6826de1d5.jpg)

4. When I open a movie or other video in full screen mode, the screen orientation remains the same, although it should be fixed in landscape mode. And I was disappointed that the full-screen does not hide the navigation and status bar.  They should be hidden when the video is in full screen mode. I hope you can.
![4.jpg](https://user-images.githubusercontent.com/45180688/140888159-1427514e-2656-407a-bec6-25783c1023c6.jpg) ![4.1.jpg](https://user-images.githubusercontent.com/45180688/140888195-b06b7128-9780-45b2-b672-e71a74ba6770.jpg)

**Comment by ThIsLinked** [comment]
# (I apologize, I did not find a spoiler to hide the images in it)
`123`
```
456
```

**Comment by jamal2362** [comment]
Suggestion 1, 3 and 4 is done.
The suggestion 2, unfortunately I can not change anything.
The suggestion 4, just use the sensor for landscape mode but the navigation bar is now gone.
