### ISSUE TITLE
Home page proposal

### ISSUE THREAD

**Issue by Liquid-Aristocracy** [jamal2362/Styx#106]
Search engine, but not Google
It's very nice to see Styx provided a wide range of search engine to choose, but it would not change the search engine on the default home page. If there's a way to change it (and the Logo probably), the experience would be more consistent.

**Comment by jamal2362** [comment]
You can enter your own search engine and logo. Everything can be found in the settings.

**Comment by Liquid-Aristocracy** [comment]
> You can enter your own search engine and logo. Everything can be found in the settings.

Turns out it's just setting update slower. Thank you!
