### ISSUE TITLE
Styx work

### ISSUE THREAD

**Issue by ArtistScope** [jamal2362/Styx#108]
**Is your feature request related to a problem? Please describe.**
We have a custom browser based on a fork of Styx and need assistance in fixing a bug. If interested in paying work, please let me know.

**Comment by ThIsLinked** [comment]
You have the wrong approach. I don’t know how abroad, but in the CIS it is not customary to ask for help like that. This is insolent, even considering that you want to financially offer the developer something for it. However, only the developer circle, that is Jamal, has the right to decide. It was just advice.

**Comment by ArtistScope** [comment]
Sorry, but I am desperate and there was absolutely no other way to contact the only person who may be able to help.

**Comment by ThIsLinked** [comment]
> @ArtistScope
Sorry, but I am desperate and there was absolutely no other way to contact the only person who may be able to help.

That's not what I meant. It is much more solidarity to try to fix the problem, and in the absence of experience - to contact. Seek advice, not work.  Moreover, you fork on its software. From his answer, I am assuming that you did not receive a license to do the public distribution. Why would he like it.

I'm just saying how it could have been and how it happened. This is just a commentary and has no effect on the question.

**Comment by ArtistScope** [comment]
And you have the audacity to talk about insolence?

**Comment by ThIsLinked** [comment]
> @ArtistScope 
And you have the audacity to talk about insolence?

I have seen such methods in practice and this is confirmed by several people with whom I have encountered this problem. So yeah, I have the nerve because I know what I'm talking about. We finish off-topic 🥃
