### ISSUE TITLE
[Maybe Not a Bug]Data size growing in size

### ISSUE THREAD

**Issue by dtoxic47** [jamal2362/Styx#11]
**Describe the bug**
The data keeps growing,so when you view the "data" section in app info in my use scenario it was about 14mb (this grows as you browse the web...and gets cleared after you exit the app) but then after some time it gets bloated to about 30mb, now it;s 55mb

i have selected to clear on exit everything except cookies so i can stay logged in in some websites
i have also enabled to block 3rd party cookies

Maybe i misunderstood how it should work but my reasoning any website data should not be stored except cookies so the data should not grow if i am logged in to 3-4 sites only? while others i just visit and do not "save" any data for those sites

**To Reproduce**
Browse the web with all options to clear everything except cookies

Watch the data grow and not cleaned
**Expected behavior**
Clean the data except unchecked options (in my case cookies)

**Smartphone (please complete the following information):**
Samsung S10+
 - OS: [Android 11]
 - Browser [Styx Browser]
 - Version [17.2]

**Additional context**
Is there something i can do on my end,or could we have to clean the data but leave us logged in to websites

**Comment by dtoxic47** [comment]
Update:
Seems that i incorrectly stated that "block 3rd party cookies" is enabled when it was not...as of now the data size remains constant at 14mb after cleaning app cache and starting the app again...will let you know if this changes so as of now everything is working as intended

**Comment by dtoxic47** [comment]
Update...data seems to be growing again

**Comment by jamal2362** [comment]
I see this discussion as unnecessary. 
How the data size is determined and created by the Android system.

Therefore, I will close here.
