### ISSUE TITLE
 Dark theme issue

### ISSUE THREAD

**Issue by davidj77** [jamal2362/Styx#11]
Please fix  it.
First image from Fulguris browser
![Screenshot_20210430-190727](https://user-images.githubusercontent.com/71226185/116765320-26016880-a9ea-11eb-87de-3f0d1ff90b11.png)

Second image from Styx browser, additionally it doesn't shows "clear" "cancel" and "set" titles.
![Screenshot_20210430-190853](https://user-images.githubusercontent.com/71226185/116765342-37e30b80-a9ea-11eb-9ce1-3410b1849075.png)
Thanks.

**Comment by jamal2362** [comment]
Thank you for the Report, i will look in to this Problem.

**Comment by jamal2362** [comment]
Fixed:
https://github.com/jamal2362/Styx/commit/f06bb680a31e461ba0737ea888dabde69f2d951f

**Comment by davidj77** [comment]
Thanks for the fix.
