### ISSUE TITLE
Google's search result gets redirected on 2nd and later clicks

### ISSUE THREAD

**Issue by Tanzin01** [jamal2362/Styx#12]
Here is a video for clear explination of the problem-

https://user-images.githubusercontent.com/41266558/218775233-d9b1c5f0-b0c1-4db2-a20b-bbd1c12d79cc.mp4

first time click works as expected, only the website url which is wanted.

but from 2nd time and later on google adds its url which is unwanted, and im assuming cost a little more time than as usual¿

**Comment by jamal2362** [comment]
This is completely normal.
This comes from the Google website.
If you try this on the computer with Firefox, for example, then it is exactly the same.
