### ISSUE TITLE
Feature Request | Tabs Management

### ISSUE THREAD

**Issue by JVariance** [jamal2362/Styx#12]
- A longpress on the 'Tabs' icon opens a new tab.
- A swipe on the search bar/toolbar lets the user switch between tabs.

**Comment by jamal2362** [comment]
Your wish with a swipe over the search/toolbar the user can switch between the tabs I can't fulfill at the moment, because I have other priorities.

However, I have implemented the first suggestion.
https://github.com/jamal2362/Styx/commit/41f9bac98838598450f0ef1ea528f388d71d4bc5

**Comment by JVariance** [comment]
> Your wish with a swipe over the search/toolbar the user can switch between the tabs I can't fulfill at the moment, because I have other priorities.
> 
> However, I have implemented the first suggestion.
> https://github.com/jamal2362/Styx/commit/41f9bac98838598450f0ef1ea528f388d71d4bc5

Schneller als die Polizei erlaubt 🚓🔥

**Comment by jamal2362** [comment]
So muss es sein 😅
