### ISSUE TITLE
[Feature Request] Cookies "Lock"

### ISSUE THREAD

**Issue by dtoxic47** [jamal2362/Styx#13]
Is it possible to implement "white/black" list for cookies,say we want a few sites to mark so we can stay logged in, we would white list cookies for those sites and after exit everything else would be deleted related to cookies be it normal or 3rd party cookies that where added trough browsing,as of now we can choose to keep cookies but they start to accumulate for sites we do not want,if we choose not to accept them then we are logged out of sites we want to save that info.

A "White/Black" list would solve this problem and i believe it would be a nice addition to overall customization and privacy that this browser already has..and i think that this might solve the problem i described in https://github.com/jamal2362/Styx/issues/11#issue-1580803958

**Comment by jamal2362** [comment]
This is currently not in planning and it is not in the future so.

There are other priorities that need to be worked off like the download manager etc.
