### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by skyGtm** [jamal2362/Styx#15]
1. Since our search requirement is different for each new tab. sometimes I want to search something in Google, and sometime in Youtube, and sometime in torrent. But only one search engine can be selected from the settings.
So, Ability to select search engine from the drop down list (at the home page), makes it more convenient to use.
Example: 
![Capture](https://user-images.githubusercontent.com/50160188/117094420-7af30500-ad83-11eb-89eb-c41089bc950d.PNG)

a. If this is going to be implemented then, there should be provision to mark few search engines as favourite (from settings, because only few search engines will be used per person.) instead of showing all the available search engines.

2. Also this torrent search engine "https://1337x.to/srch?search=" is my favourite, please try to add this. This might be useful to others too.

**Comment by iamtalhaasghar** [comment]
You can add your torrent search engine using "_General >> Search Engine >> Custom URL_" option.
