### ISSUE TITLE
custom downloader

### ISSUE THREAD

**Issue by BioBut** [jamal2362/Styx#16]
please add custom downloader
reference:
https://github.com/CookieJarApps/SmartCookieWeb

**Comment by jamal2362** [comment]
Hello,

According to my first findings with this custom downloader, it is bugged. Therefore, this one does not come in Styx.

**Comment by BioBut** [comment]
ok 
you can add external support downloader
automatically ask  open other browser/apps
example:
download start with open directly other browser/apps
