### ISSUE TITLE
[Feature Request] Socks5 Proxy

### ISSUE THREAD

**Issue by iamtalhaasghar** [jamal2362/Styx#20]
It would be great to **Socks5 proxy** option in _styx_. With this feature we can then use TorServices app to route all traffic from styx over tor using "127.0.0.1:9050" socks5 proxy settings. Styx with Orbot is also a great option but i find Orbot a bit sluggish.

**Comment by jamal2362** [comment]
Hey,

Have you tried to enter the port manually ?

![Screenshot_20210512-082025](https://user-images.githubusercontent.com/15986930/117927759-f3fdd980-b2fa-11eb-8350-c0009c598ec6.jpg)

**Comment by iamtalhaasghar** [comment]
I get following message:
<br>
**This is a SOCKs proxy, not an HTTP proxy.**

It appears you have configured your web browser to use this Tor port as an HTTP proxy.
This is not correct: This port is configured as a SOCKS proxy, not an HTTP proxy. If you need an HTTP proxy tunnel, use the HTTPTunnelPort configuration option in place of, or in addition to, SOCKSPort. Please configure your client accordingly.
See https://www.torproject.org/documentation.html for more information.

**Comment by jamal2362** [comment]
Thank you for the Report.
I will look soon into this Problem.

**Comment by jamal2362** [comment]
After much deliberation, I decided to remove the proxy.
