### ISSUE TITLE
Izzyondroid says the source code is unavailable

### ISSUE THREAD

**Issue by TheHCJ** [jamal2362/Styx#21]
**Describe the bug**
Izzyondroid has an outdated version of the app

**To Reproduce**
1. Go to IzzyOnDroid F-Droid
2. Go to Styx Browser
4. See the issue

**Expected behavior**
It should have an updated version without any ani-features

**Comment by jamal2362** [comment]
I do know whats wrong with Izzy's repo.
He must fix it.
