### ISSUE TITLE
Feature Request - Enable 3rd party downloads forwarding

### ISSUE THREAD

**Issue by Trolljan** [jamal2362/Styx#21]
The overallll app experience is pretty good, however please add an option to forward the downloads to Third party downloader apps like ADM ,1DM or Navi as they provide more features and efficiency than the stock one. Also is it possible To have multiple  remote hosts file sources currently it allows only one.

**Comment by jamal2362** [comment]
The redirection for downloads is a good idea. I'll see if this is feasible with Styx.

The ad blocker remains for the time being so.
This is a simple ad blocker.
If you want a more advanced ad blocker, there are many alternatives that work system wide like AdAway, Adguard etc..

**Comment by jamal2362** [comment]
@Trolljan 
I took a closer look at redirecting to another download app.

The easiest way is to press and hold a download link and then press Share.
From there you can select the download app of your choice.

From there I close this issue.

![Screenshot_1621085264](https://user-images.githubusercontent.com/15986930/118362967-689e7580-b592-11eb-9f2d-3b5f342f00bd.png) ![Screenshot_1621085269](https://user-images.githubusercontent.com/15986930/118362970-6b996600-b592-11eb-8c64-f3bc8b224742.png) ![Screenshot_1621085278](https://user-images.githubusercontent.com/15986930/118362973-6cca9300-b592-11eb-8466-696c6cbcb2d9.png)
