### ISSUE TITLE
[Feature Request] Ability to add "Custom Icon url" for the "Custom SearchEngineUrl"

### ISSUE THREAD

**Issue by skyGtm** [jamal2362/Styx#22]
BECAUSE Adding a custom searchEngine URL shows a Styx browser Icon at the home page.

**Comment by jamal2362** [comment]
This should be feasible, but does it really make sense?

**Comment by jamal2362** [comment]
The suggestion was added in Styx.
https://github.com/jamal2362/Styx/commit/f213fa93c7b8bc8a49513ea0dcbfaa735a7fa360
