### ISSUE TITLE
[Feature Request] Ability to select different search engine from homepage

### ISSUE THREAD

**Issue by skyGtm** [jamal2362/Styx#24]
Since, for each new tab search engine requirement might be different. So it would be better to have dropdown list of search engines which can be directly selected from homepage. as mentioned in #15
Don't you think this feature is intriguing and beneficial for user? May I know why #15 issue was closed (I understand that custom url can be added from settings; but there was another feature request too)

**Comment by jamal2362** [comment]
Hello,

For this feature I need help, because I do not know how exactly this should be implementable.
I currently don't know any way how to implement this.

Maybe there is someone who is helpful in this matter.

Sorry for closing #15 without a message.

**Comment by jamal2362** [comment]
This feature request is closed for now.
