### ISSUE TITLE
Add a reload button

### ISSUE THREAD

**Issue by peat80** [jamal2362/Styx#25]
**Is your feature request related to a problem? Please describe.**

Would love to have an reload button in the toolbar. You can have all navigation tools at the bottom but still have to scroll up all the way to reload a webpage.

**Describe the solution you'd like**

An option to replace the home button with an reload button in the toolbar for example would be awesome.

**Describe alternatives you've considered**

**Additional context**

**Comment by jamal2362** [comment]
A button to reload the web page should be in the bar.
