### ISSUE TITLE
[Feature Request] Adding multiple CustomURL for search engines.

### ISSUE THREAD

**Issue by skyGtm** [jamal2362/Styx#25]
I don't think it would be good to ask for adding search engine as #13, #15 (number 2).
I have few other search engines in my mind which I use daily, but ability to add only one CustomURL is limiting to use the browser.
So it would be better to have ability to add multiple CustomURLs by the user himself.
A `dialog box` where a user can input the following fields.
Name of search Engine:
Search URL:
ICON URL:  (As mentioned in #22)

I believe above mentioned feature will be beneficial to most of the users.

**Comment by jamal2362** [comment]
Hello,

Currently this is not feasible.
Sorry.
