### ISSUE TITLE
Feature Request: Add configuration for "there's a third party app available" popup 

### ISSUE THREAD

**Issue by m-rey** [jamal2362/Styx#26]
I was wondering if it would be possible to add a config in the settings regarding the popup "there's a third party app available".

While I understand that it's nice to be informed about the possibility of opening the website in a dedicated app, often times I just want wo browse the site, without having a nagging popup showing up almost every time.

Additionally, I'm sure there are also people that would like to open the website in the dedicated app every time, without being asked.

Therefore, being able to configure that part in the settings would be very helpful.

**Comment by jamal2362** [comment]
I can not reproduce the error that it asks again every time you click on no or yes in the dialog.
In the settings under Apps you can change the option if you want to be redirected or not.

A dialog for dont ask again is not necessary because you will only be asked once.
