### ISSUE TITLE
[Feature Request] Don't exit after closing the last tab

### ISSUE THREAD

**Issue by tsiflimagas** [jamal2362/Styx#27]
Currently, closing the last opened tab leads to exit the browser. To me, it would be better to either immediately open a new tab, or be left with an empty view (as it happens with chrome, ddg, etc). Either it'll be default or there'll be an option for it, I guess that's your call, If you accept implementing it.

**Comment by jamal2362** [comment]
Hey,

Do you have try to turn this option off ?
![Screenshot_20210517-193324](https://user-images.githubusercontent.com/15986930/118532111-dee3d900-b746-11eb-8136-291a05d2c92e.jpg)

**Comment by tsiflimagas** [comment]
This was there all the time?😅😂 I usually don't miss such stuff, sorry for that.

**Comment by jamal2362** [comment]
This feature was implemented between v6.0.0 to v7.0.0, so it's been a while :D
