### ISSUE TITLE
[Feature Request] Option to tint site loading bar with accent colour

### ISSUE THREAD

**Issue by tsiflimagas** [jamal2362/Styx#28]
Tinting the site loading bar with accent colour would look good I think, and maybe would also make it a bit more conspicuous.

**Comment by jamal2362** [comment]
Hello,

I have had a look at this, it doesn't look as great as you'd imagine, so it doesn't get a place in styx.

Sorry.

**Comment by tsiflimagas** [comment]
It's ok, I like the ui anyways :)
