### ISSUE TITLE
Bottom bar Tabs instead of side navigation (feature request))

### ISSUE THREAD

**Issue by RanbirSingh** [jamal2362/Styx#3]
Hi Jamal! man you did a great job. recently you fixed all the bug's now this browser become really stable..i have suggestions for the tabs bottom bar for tabs navigation will provide great ui experience.. like firefox browser.. Palese add the feature if you have time.. that would be great..

**Comment by jamal2362** [comment]
Feature added in v6.8.0.

![Screenshot_20210301-175219](https://user-images.githubusercontent.com/15986930/109530342-e59f7000-7ab6-11eb-8fc2-6804c0fffcf3.jpg)
