### ISSUE TITLE
No need to translate numbers '0' - '9'

### ISSUE THREAD

**Issue by OliverLew** [jamal2362/Styx#30]
Such as those in search suggestion number option. These characters are universal. I think a lot of people are even more familiar with/sensitive to Arabic numbers than the corresponding words in their own language.

**Comment by jamal2362** [comment]
In Arab countries, the numbers 0-10 are just that. They do not use the universal number.

**Comment by OliverLew** [comment]
What I meant was numbers like 0-9 does not need translation, users all around the world know these numbers 0-9. '0'-'9' themselves are called Arabic numbers, not limited to Arab countries. Maybe a misunderstanding due to my bad English.

However, in the strings.xml file, these numbers are translated, e.g. in my language:

https://github.com/jamal2362/Styx/blob/c17132422042337b0b861fda34855746fe8bb8d8/app/src/main/res/values-zh-rCN/strings.xml#L399

And I see the translations used in the "Search suggestions (number)" option. 

I think the numbers '0'-'9' are just '0'-'9', they don't need to translate into other things ('2' -> '二‘ in Chinese).

**Comment by jamal2362** [comment]
Ok, now I get it, agreed. Will do so.

**Comment by jamal2362** [comment]
Done :)

https://github.com/jamal2362/Styx/commit/810ba8a1a87537603ac787632f7fdb71e3b3ca59
and
https://github.com/jamal2362/Styx/commit/4dfa37de1463208164b3930e68d574cc1d68559f
