### ISSUE TITLE
View page's source code crashes Styx.

### ISSUE THREAD

**Issue by esdreesh** [jamal2362/Styx#32]
Page tools/View page's source code crashes Styx irreversibly (forces close)

**Comment by jamal2362** [comment]
Yes I am aware of this and I am looking into a solution. This happens when the source from the side is too long.

**Comment by jamal2362** [comment]
Ficed with this commit:
https://github.com/jamal2362/Styx/commit/3540ad048582385fdd32dd49b0ffbeeec3ef743f
