### ISSUE TITLE
Add Ad-block Filter.

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/Styx#33]
Will we be able to add more than one ad filter in the future?

**Comment by bakinazik** [comment]
It will be a more efficient experience if you include language filters in the ad filter.
https://github.com/AdguardTeam/AdGuardFilters

**Comment by GrpeApple** [comment]
One could also use web extensions such as [uBlock Origin](https://github.com/gorhill/uBlock)

**Comment by xxxcrow** [comment]
about ublock origin, it's nice that for firefox or fennec, websites can't detect that i am using an adblock
it would be awesome to make it undetectable 😃

**Comment by GrpeApple** [comment]
Some may also use Pi-hole or NextDNS, Chrome has a DNS Feature built-in to it (I am using Canary, not sure if on production) though that would probably require more effort, but it also is undetectable.

**Comment by Slion** [comment]
Related to https://github.com/Slion/Fulguris/pull/205

**Comment by jamal2362** [comment]
It is currently in progress.
By @Helium314

When exactly this will come, I do not know yet.

**Comment by jamal2362** [comment]
Here is the current process.

First of all, thanks to @Helium314 for the revised adblocker.

There are still some things to be done.

https://github.com/jamal2362/Styx/commit/09aff5f64ccf60e93ab5411cb1895c09eb18d43a

**Comment by Ultimatinium** [comment]
Wow, now I see the progress, I will wait for the future update...
