### ISSUE TITLE
Keyboard overlaps on searchbar and browser does not adjust (Tablet)

### ISSUE THREAD

**Issue by AlanSmythe** [jamal2362/Styx#34]
Hello,

I downloaded the Styx browser on an old tablet, a Samsung Galaxy Tab A. I like to use my tablet on landscape mode. I noted when using a different browser on my main page (Duckduckgo) when typing in the search bar, the browser adjusts to my keyboard so I can still see the bar. Styx however, does not adjust, and the keyboard covers the searchbar.

The reason I think this is an issue with Styx is because I used a different browser on the same website (Duckduckgo) in both browsers, The alternate browser was able to adjust and Styx could not. I report this to help Styx become a better browser, I think it has potential.

**Comment by Slion** [comment]
Thanks for reporting this issue. I'm not quite sure I get it though, Could you provide some screenshots?
Please also try [Fulguris ](https://slions.net/resources/fulguris.10/) which is the browser Styx is based on and report if this is a problem there too.

**Comment by AlanSmythe** [comment]
![overlap](https://user-images.githubusercontent.com/60452637/120053611-1d0bb300-bff9-11eb-94e1-5254b9582023.png)

**Comment by Slion** [comment]
Could not reproduce with [Fulguris ](https://slions.net/resources/fulguris.10/) on a Galaxy Tab S6 running Android 11.
Which version of Android is you tablet running?
![Screenshot_20210529-033422_Fulguris](https://user-images.githubusercontent.com/6508892/120054279-53642500-c02f-11eb-95a5-d960204ba3a9.jpg)

**Comment by Slion** [comment]
@AlanSmythe Please try with Fulguris and see if it works.

**Comment by AlanSmythe** [comment]
In general, I try to stick to open source apps, but I tested fulguris and I ran into the same issue. My Galaxy Tab A is old and I have it running Lineageos with Android 9, the latest version that it can support.

![fulgris](https://user-images.githubusercontent.com/60452637/120055298-2dc12680-c003-11eb-885c-1bed00fc8fae.png)

**Comment by Slion** [comment]
> In general, I try to stick to open source apps

Well then you are in good hands with Fulguris too, you can find the source code on [GitHub](https://github.com/Slion/Fulguris) as well. As I said earlier Styx is a downstream fork from Fulguris and the only reason there is a Styx is because **Fulguris is open source**.

Thanks for testing that. So it seems to be a bug on your Android 9 port. However some apps can still workaround that bug somehow. Could you tell us which open source browsers you tested do not have that issue?

**Comment by AlanSmythe** [comment]
> > In general, I try to stick to open source apps
> 
> Well then you are in good hands with Fulguris, you can find the source code on [GitHub](https://github.com/Slion/Fulguris) as well. As I said earlier Styx is a downstream fork from Fulguris and the only reason there is a Styx is because **Fulguris is open source**.
> 
> Thanks for testing that. So it seems to be a bug on your Android 9 port. However some apps can still workaround that bug somehow. Could you tell us which open source browsers you tested do not have that issue?

I used the default Lineageos Jelly browser that came with it as well as a browser called Smartcookie and they both adjusted to my keyboard in Duckduckgo.

**Comment by Slion** [comment]
Thanks, that is helpful. Are you talking about this [SmartCookiWeb](https://github.com/CookieJarApps/SmartCookieWeb)?
Just to be sure.

**Comment by AlanSmythe** [comment]
> Thanks, that is helpful. Are you talking about this [SmartCookiWeb](https://github.com/CookieJarApps/SmartCookieWeb)?
> Just to be sure.

Yes that is the one.

**Comment by jamal2362** [comment]
Hi,

I cannot reproduce the issue on my Chromebook and Xiaomi Mi Pad 4 Tablet.

I think it is the keyboard you are using or something is going wrong in the rom.

Thanks for reporting but I'll close here.
