### ISSUE TITLE
Add domain specific settings.

### ISSUE THREAD

**Issue by Raj52537** [jamal2362/Styx#38]
Add domain specific settings so that global settings can be override per domain. This allows user to give specific permission per site.
This feature is present in privacy browser.

**Comment by jamal2362** [comment]
Hi,
Can you explain this to me in more detail?
What is missing exactly?

To make it easier for me to understand, pictures are also allowed.

**Comment by Raj52537** [comment]
It is a feature available in hermit apl and I have also seen it in "privacy browser"
this feature enables users to have per site (domain)settings
Like for example Iwant to disable cookies and javascript or say images normally but want to enable it for specific site like twitter.com
Privacy browser also provide wildcard support to set this setting for all su domains etc.

**Comment by Raj52537** [comment]
Here is the screenshot from "privacy browser" for quick reference. 
It takes all global settings but for specific domain 
In hermit this feature is called local apps
![Screenshot_20210607-210241019](https://user-images.githubusercontent.com/81609264/121048172-328c9400-c7d4-11eb-950c-513a85d76e45.jpg)

**Comment by Slion** [comment]
@Raj52537 This feature is already on the roadmap of the upstream fork: https://github.com/Slion/Fulguris/issues/159
