### ISSUE TITLE
[feature request] add cookie isolation

### ISSUE THREAD

**Issue by xxxcrow** [jamal2362/Styx#39]
Firstly i want to say thanks to the developer and all the people involved, if any
Thank you guys, you really do a great job, and it's amazing to see some outstanding independent foss project, god bless you ✨
Styx browser has many interesting and never seen features for me (also it's fast, very fast)
I tried Fennec first, it's good, but it's terribly slow...
but they have that function "cookie isolation", i don't know exactly what that means, but sounds very "privacy oriented" and so on 😅
If it's possible to add in the future it would be very nice
Thank you 💫

**Comment by jamal2362** [comment]
Thank you so much for the kind words :)

I will have a look at it.
For info: In Styx it is also possible to block third party cookies.
You can find this under the privacy settings. 😁

**Comment by jamal2362** [comment]
I have looked again this feature is known to me only for Gecko-Based Browser of therefore I make here to since this is so not convertible up-to-date.
