### ISSUE TITLE
data:text/html;charset=utf-8;base64,

### ISSUE THREAD

**Issue by xxxcrow** [jamal2362/Styx#40]
When i have no connection(or bad connection)
this shows in the address bar (but not if i press it)
but if i press it multiple times it changes the url to "data:text/html;charset=utf-8;base64,"
i think there should be a message that says that i have no connection, and it shouldn't be selectable 👍 or just no message 😅

**Comment by jamal2362** [comment]
Thanks for the issue Report.
I will fix it in the next version ☺️

**Comment by jamal2362** [comment]
Fixed :)

https://github.com/jamal2362/Styx/commit/df27231110c721d3964347e1c4ba47bf8e86c46b

**Comment by xxxcrow** [comment]
But where did the beautiful screen about "connection" and "reload" go??? 😳
now i have only default android "webpage not available" screen

**Comment by jamal2362** [comment]
A fix for that is coming later today.

The reload is out because you have the refresh button at the top.

**Comment by xxxcrow** [comment]
good job, waiting for more updates ❤️

**Comment by jamal2362** [comment]
Now it should be better than before. ☺️
