### ISSUE TITLE
Home Button On Address Bar

### ISSUE THREAD

**Issue by gitdebpro** [jamal2362/Styx#41]
Please provide an option to have home Button on address bar while the later is set to bottom I mean the address bar is set to bottom.

**Comment by jamal2362** [comment]
Hi :)

Did you mean that? 
![photo_2021-06-07_21-09-59](https://user-images.githubusercontent.com/15986930/121074892-c3636f80-c7d4-11eb-9850-6ce4b48395f0.jpg)

**Comment by gitdebpro** [comment]
no I mean only the home icon on address bar when it is set to bottom.

**Comment by gitdebpro** [comment]
I mean this home Button on bottom address bar at the begining![121074892-c3636f80-c7d4-11eb-9850-6ce4b48395f0.jpg](https://user-images.githubusercontent.com/81520025/121077651-8491e180-c7f5-11eb-8d92-b5d00242d549.jpg)

**Comment by jamal2362** [comment]
Hello,

I'm sorry but this feature is currently not planned and therefore I close here.

I can recommend you to activate the second navigation bar, so you have everything in one place.

**Comment by gitdebpro** [comment]
> Hello,
> 
> I'm sorry but this feature is currently not planned and therefore I close here.
> 
> I can recommend you to activate the second navigation bar, so you have everything in one place.

OK Thanks anyways
