### ISSUE TITLE
12.6 err_connection_time_out missed

### ISSUE THREAD

**Issue by xxxcrow** [jamal2362/Styx#42]
Continuing previous issue and "webpage not available" rework
I'm creating a new issue because previous one is not already related to the page itself 😅
It's good to keep everything organized 👍
So, new "website not available" page is working, but not for "err_connection_time_out"

**Comment by jamal2362** [comment]
Thx 😁

Yes, I know, in some rare situations the theming of error page doesn't work for some reason. It seems to depend on the timing.

I can watch again, but it may not be possible to fix this bug.

**Comment by Slion** [comment]
Related to https://github.com/Slion/Fulguris/issues/208
