### ISSUE TITLE
APKs flagged

### ISSUE THREAD

**Issue by IzzySoft** [jamal2362/Styx#45]
Just to let you know that your latest 2 releases [got flagged](https://www.virustotal.com/gui/file/9f11c43de44d7bf6effba3647c6c683d08ff4cb6dd6011ee3c769e9505fb5219/detection/f-9f11c43de44d7bf6effba3647c6c683d08ff4cb6dd6011ee3c769e9505fb5219-1623214129) by Kaspersky and ZoneAlarm. No idea what triggered that, but you might wish to check.

**Comment by jamal2362** [comment]
Hello,
I have not included anything else in my code that could trigger this.
I think it is more likely a false/positive message for whatever reason. 
I noticed on IzzyOnDroid that some releases are clean and the next one shows that it is not clean.
For whatever reason...

**Comment by IzzySoft** [comment]
No worries, I share your opinion on this. Good you are already aware of the situation – I just wanted you to be prepared when approached by "enraged users".

You might also note I ignored a 3rd engine (it's a rather minor one and in the past had a lot of false positives). So I count this as "2 engines reported" as it was two rather major ones. Still, as long as it's less than 5, a false positive is the most likely thing. As we cannot look inside them, it's hard to know what triggered them – or what measure would alleviate the problem.

Again, to be absolutely clear: All I wanted to say is that those two "flagged" the APK – not that I assume there's something wrong with the APK (most likely rather a snake-oil problem :stuck_out_tongue_winking_eye:). So heads up, stay strong :smiley: – and :crossed_fingers: whatever it is will soon be gone!

**Comment by jamal2362** [comment]
What I can imagine is that it is due to the edit new home page. If I look more closely why then I see that he reports something because of HTML and hosts.

The 2 messages may also have been triggered, because I have a hosts.txt in the app to block advertising. Maybe something is bothering him too.

I don't know, it's funny anyway. Sometimes VirusTotal strikes and then it doesn't. 😄

In the end I will never know why it triggers. 😂

**Comment by IzzySoft** [comment]
Well, as long as it's just one engine or two… Though of course if you have an idea what to try, getting them all green is to be preferred. Else feel free to close this issue – you're informed, mission accomplished :smile:

**Comment by jamal2362** [comment]
All right then I close here 😊
