### ISSUE TITLE
Option to disable the long press to "Tab" Icon, open a new Tab.

### ISSUE THREAD

**Issue by jamal2362** [jamal2362/Styx#46]
Option to disable the long press to "Tab" Icon, open a new Tab.

**Comment by jamal2362** [comment]
https://github.com/jamal2362/Styx/commit/fd04f5fd44249ab2fb78e5182532f45f4f0f1bdc

**Comment by xxxcrow** [comment]
I didn't know it was possible 😂

**Comment by jamal2362** [comment]
Now you know 😂
