### ISSUE TITLE
Dark theme & Contrast

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/Styx#47]
It would be more useful if the contrast did not affect the images in the page when the contrast is increased. Darkens the content and images are not fully understood. So it should definitely be prevented from affecting the pictures.

**Comment by jamal2362** [comment]
Show me a picture please

**Comment by bakinazik** [comment]
This is what it looks like when you affect pictures.
![22](https://user-images.githubusercontent.com/61169988/121757335-e7e97f80-cb25-11eb-8ee5-2b317e078f8f.png)
![11](https://user-images.githubusercontent.com/61169988/121757339-e91aac80-cb25-11eb-8a33-348cb83d418e.png)

**Comment by xxxcrow** [comment]
Where is this contrast option? 🙄

**Comment by jamal2362** [comment]
![Uploading Screenshot_20210612-082659.jpg…]()

**Comment by jamal2362** [comment]
Unfortunately, I have no influence on the contrast since it is rendered by the system.
This affects the whole webview and images cannot be freed from it.

**Comment by xxxcrow** [comment]
I think that's the point of this mode, also isn't it hard to exclude images from this rendering mode? 
Because without images what it would be? Just font settings? May be easier just to set up the fonts then
