### ISSUE TITLE
White icons in settings

### ISSUE THREAD

**Issue by xxxcrow** [jamal2362/Styx#48]
**Description**
Where are the colors of the settings list? 
Now they are all white
I thought everyone noticed and it would be fixed in 12.9

**To Reproduce**
1. Open the browser V12.8-12.9 (I hope not earlier 12.8)
2. Go to the settings

**Expected behavior**
Colored icons as before 12.8

**Comment by jamal2362** [comment]
Look at this commit.
I have change it, because of a user request.

https://github.com/jamal2362/Styx/commit/1ea191da3a5bef4294feb8185a4935080273d004

**Comment by xxxcrow** [comment]
@jamal2362 oh, it was a lot of work 😅
Personally, i liked the colors
But wasn't it possible to have a switch to turn and turn it off at least (or some theme/accent stuff)
Because now all my circles are white with white icons on them 😅
White on white =! Readable 😃

**Comment by xxxcrow** [comment]
![Screenshot_2021-06-14-02-27-42-782_com jamal2367 styx](https://user-images.githubusercontent.com/24483751/121819599-23b44e80-ccb8-11eb-880d-36f4f9077ec5.jpg)

**Comment by jamal2362** [comment]
Oh it shouldn't look like that... 😮

Which Android version is used ?

**Comment by xxxcrow** [comment]
@jamal2362 oh, I see, the probablem is in phone's dark mode 
I use MIUI Android 11
Usually phone's dark mode rarely breaks anything, but it happens, but I didn't expect it here 😬

**Comment by jamal2362** [comment]
Do you have Telegram? If yes, then write to me.

I have a few questions and it would take too long here. 😁

My name there is @jamal2367

**Comment by xxxcrow** [comment]
@jamal2362 of course, I have 😄

**Comment by jamal2362** [comment]
An incorrect system setting was to blame. That's why I'm closing here.
