### ISSUE TITLE
Gestures

### ISSUE THREAD

**Issue by janTaja** [jamal2362/Styx#49]
I’d like to have customizable gestures. For example, I’m used to having two finger swipes right/left for navigating back/forward, down for stop/reload and swiping from bottom corners for showing the toolbar. Having this feature would be useful because you don’t have to scroll the page for showing the toolbar (if it’s set to “hide when scrolling down”) and searching for the action you need in the menu this way.
The idea is taken from Naked Browser.

**Comment by jamal2362** [comment]
Do you have look to this feature?
![Screenshot_20210614-102358](https://user-images.githubusercontent.com/15986930/121862051-bd045480-ccfa-11eb-92fa-8917483ede60.jpg)

![Screenshot_20210614-102414](https://user-images.githubusercontent.com/15986930/121862067-c2619f00-ccfa-11eb-8715-f5b45a208b32.jpg)

**Comment by janTaja** [comment]
“This feature” is not gestures.
Okay, I see you don’t want to add faster ways to do certain actions, you could at least add the appropriate label here :D “Gestures — feature already implemented” no, it’s not.

**Comment by jamal2362** [comment]
If it bothers you then find the right browser and use that. It is there what is there and is good.
