### ISSUE TITLE
One click search in other search engines[featute]

### ISSUE THREAD

**Issue by Tanzin01** [jamal2362/Styx#5]
It would be nice to show search engine at the bottom when something is being written in the url text box.

People who use the web for research purpose heavily will be benefited from it. Also i(may be many others) can leave trash, spying firefox for good.

![Screenshot_2023-01-31_14-43-31](https://user-images.githubusercontent.com/41266558/215711274-614ba6e1-ea4c-4b52-b2ed-04e6bd5c8c9d.png)
something like this.

**Comment by jamal2362** [comment]
This is already possible, choose a search service of your choice and you will receive suggestions.

**Comment by Tanzin01** [comment]
Thanks. found it.

It seems like, exactly one letter need to be written for search suggestions.  pick a engine. Now start writting again your query from start.

If possible, it would be nice, to have the suggestions all time(a option in  settings). Whenever one pick a suggestion(search engine), the written text in search box would be searched.

best regards
