### ISSUE TITLE
Bookmarklets

### ISSUE THREAD

**Issue by janTaja** [jamal2362/Styx#50]
If the “Bookmark in new tab” setting is enabled, bookmarklets open in new tab too. I’d like to always have them opening in current tab, i. e. bookmarklets support.

**Comment by jamal2362** [comment]
Then turn off the option then this will no longer open in a new tab.

**Comment by janTaja** [comment]
That’s not a solution at all, I want bookmarks to open in new tab. Could you explain why you don’t want this feature, please? Bookmarklets are very useful, especially in mobile browsers.

**Comment by jamal2362** [comment]
The feature is already included in Styx.

Do you have look here ?
https://abload.de/img/screenshot_20210614-1axk25.jpg

**Comment by janTaja** [comment]
What I’m suggesting is literally not having to turn on and off the thing every time I want to use a bookmarklet. It takes time, there’s no point in making it harder than it could be.

**Comment by jamal2362** [comment]
Then just turn it off or on depending on how you want it. Where is the problem?
