### ISSUE TITLE
[Discussion] Improve Styx user experince

### ISSUE THREAD

**Issue by M86xKC** [jamal2362/Styx#52]
After using a chromium-based web browsers for a long time, and now switching Styx for a month I've noticed many improvements to the overall user experience specially the speed improvements, but also noticed some small issues that could be improved 😉

**Is your feature request related to a problem? Please describe.**

No.

**Bug Report:**

- Recently a feature was added to long-press the "tabs" icon to create a new tab. I like the idea but it does not work if you show "Toolbars at the bottom" and enabled "tabs in the navigation drawer". for some reason: 

<details>
<summary>Screenshot</summary>

![image17](https://user-images.githubusercontent.com/31791780/121987983-1024e880-cd89-11eb-8ce6-4272ebede775.png)

</details>

**Feature Requests:**

1. Switch tabs when swiping across the URL-bar

<details>
<summary>Video 1</summary>

![Switch_Tabs_Quickly_on_Google_Chrome_Android](https://user-images.githubusercontent.com/31791780/121913212-b983c400-cd20-11eb-895b-fa50fdd84136.gif)
[Credit](https://www.youtube.com/watch?v=tulB5Y-sm40&t=87s)

</details>

2. Open menu; select an option with one tap (pressing the three vertical dots and dragging down/up from there without lifting to choose an option in the menu)

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/31791780/121924617-9a3e6400-cd2b-11eb-8bf7-c78b9da0bf04.mp4

</details>

4. Make it easier to switch between incognito & normal tabs, now you have to close the incognito tab to go back to normal mode, please correct me if I'm wrong?

Also make creating new tabs easier for users with bottom toolbars, when long pressing the tabs icon, it  should pop-up a dialog to choose between normal or incognito. Below design for reference:

<details>
<summary>Screenshot</summary>

![tab-long-press-chrome](https://user-images.githubusercontent.com/31791780/121989056-fb495480-cd8a-11eb-973f-20a76d1e533b.png)

</details>

5. Easily change per-site permission by pressing or long-pressing the lock icon besides the url/page title, Below design for reference:

<details>
<summary>Details</summary>

![photo_19](https://user-images.githubusercontent.com/31791780/121991546-68f77f80-cd8f-11eb-8dc0-534a9d9c522d.png)
![photo_20](https://user-images.githubusercontent.com/31791780/121991139-9e4f9d80-cd8e-11eb-8147-b0baf45ad745.jpg)
![photo_33](https://user-images.githubusercontent.com/31791780/121991155-a7406f00-cd8e-11eb-8427-fc5822bd7596.jpg)
![photo_32](https://user-images.githubusercontent.com/31791780/121991163-aa3b5f80-cd8e-11eb-88a6-6d1397003582.jpg)

</details>

6. Make it easier to bookmark a webpage through the bookmark icon in the screenshot below; like when you long-press the tabs icon for a new tab.

<details>
<summary>Screenshot</summary>

![image17](https://user-images.githubusercontent.com/31791780/121987983-1024e880-cd89-11eb-8ce6-4272ebede775.png)

</details>

7. Long-pressing back & forward button (in the above screenshot) to show history timeline, Below design for reference:

<details>
<summary>Screenshot</summary>

![Screenshot_20190130-092356](https://user-images.githubusercontent.com/31791780/121988692-5464b880-cd8a-11eb-883d-cfa9e97d0ecc.png)

</details>

8. Option to open links in incognito directly, basically when you pressing/clicking a link in another app, it immediately open the new tab in normal mode. So instead of that open it in incognito mode. Below design for reference:

<details>
<summary>Details</summary>

![firefox_browser_open_in_incognito](https://user-images.githubusercontent.com/31791780/121989671-06e94b00-cd8c-11eb-8100-18129cbbe180.jpg)

</details>

9. Add more granular controls in the permission page in settings

- access clipboard
- access motion sensors
- background sync ...etc

10. Option to automatically/manually force an update to the ad-block blocklist included by default in the app.

11. Add a domain redirect option; for example when opening reddit.com redirect it to old.reddit.com instead.

**Describe the solution you'd like**

This is basically my wish-list of features I want to see in Styx, This is not a hard list of requirement for the developer by any means. Complicated feature regarding their technical implementations and features that the developer does not agree with can be ignored.

**Describe alternatives you've considered**

Most of these features just makes things a little bit easier for the user experience.

**Additional context**

None

**Comment by xxxcrow** [comment]
Also, incognito mode notification "tab to open" is cool, but may be if it's possible to add "close on swipe"

Yeah, a lot of features from chrome/brave I miss, toolbar swipe, fast settings

Also, my personal problem with settings, a lot of settings I don't know what they do and where I can them 😅

**Comment by M86xKC** [comment]
> Also, my personal problem with settings, a lot of settings I don't know what they do and where I can them 

Please be more specific and try to provide helpful feedback that'll help improve things.

**Comment by xxxcrow** [comment]
@M86xKC sometimes it's hard to find something, and a lot of settings I don't know what they do, need to switch and go back to see the results, and then go back to find it
It's just my personal experience, it seems I just have issues with any settings
Just wanted to mention it because every update brings new switch to the settings, and it's a lot of them there already, I'm afraid it can become a bit like overcrowded 😅

**Comment by Ultimatinium** [comment]
I hope @jamal2362 can make the settings more cleaner, like there are many settings scattered around...

**Comment by Slion** [comment]
@M86xKC Thanks for using a Web Browser based on [Fulguris](https://github.com/Slion/Fulguris).
That's some great feedback you are giving here I really like the parts about [Domain settings](https://github.com/Slion/Fulguris/issues/159) and [Page history](https://github.com/Slion/Fulguris/issues/174).
I encourage you to contribute to those focused tickets to increase the likelihood that they will be taken into account during the implementation phase.

I see you are using the bottom toolbars, you may want to give Fulguris a try there as some of the concepts may have bin lost in Styx. Also when it comes to creating a new tab the concept in Fulguris is that you don't create a new tab explicitly it does that for you automatically instead you may want to close tabs from time to time.

**Comment by jamal2362** [comment]
In the future, this is certainly feasible. But currently I lack the time. When I have more free time again, then I look at this again.
