### ISSUE TITLE
Add incognito web search button

### ISSUE THREAD

**Issue by xxxcrow** [jamal2362/Styx#53]
**Describe the bug**
New tab from incognito opens a normal window

**To Reproduce**
1. Open the browser
2. Open new incognito mode window
3. Open any website
4. Long press on a word, or sentence
5. Press web search

**Expected behavior**
I'm not sure, but in my research I found two types of behavior
1. No web search suggestion (tested: chrome, brave)
2. Private search suggestion (tested: Firefox)

**Smartphone (please complete the following information):**
Experienced bug on Xiaomi Mi 9 Android 11, Styx 13.0
Tested other browsers on the same device
Also tested possible types of behavior on pixel 3a

**Comment by jamal2362** [comment]
Hi,

This is not a bug.
Just hold down a link and select Open in a new tab.
Then a new Incognito tab will be opened.

If you click it via the system's own web search then this is handled by the system. Unfortunately I have no influence on it.

**Comment by xxxcrow** [comment]
I'm exactly talking about "web search" dialogue USING THE BROWSER after selecting any text, not a hyperlink
Selecting text will not suggest any open in new tab

**Comment by xxxcrow** [comment]
@jamal2362 and also, in other browsers they have influence on this menu
For example Firefox suggests "Private search", no "Web search"
