### ISSUE TITLE
Slowdown due to Animation

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/Styx#54]
**Is your feature request related to a problem? Please describe.**
Splash screen slowdown due to animations.

**Describe the solution you'd like**
If you disable the (splash screen specific) animations, you will get a faster splash screen. Especially webview based browsers seem cumbersome due to their splash screen animations. "**loading bar & search bar**" If it is a specially added feature, an option must be added so that it can be disabled from the settings. It will be useful for people with low-system phones.

**Comment by jamal2362** [comment]
Hi,

Currently there is no need to install this, so I will close here.

The browser already has too many settings, at some point it's enough.
