### ISSUE TITLE
Add More Privacy Options

### ISSUE THREAD

**Issue by Ultimatinium** [jamal2362/Styx#58]
At the [Settings - Privacy] on Privacy add more features like Secure DNS , HTTPS Everywhere , And Broadcast IP (WebRTC Performance)

On Privacy Menu :

Add Secure DNS Menu :
> On Secure DNS menu :
Add Toggle Switch [On/Off]

> On Secure DNS menu :
Add selection box
>> In the selection box :
Add [Automatic (Current Service Provider)]

and

[Custom Provider (like CloudFlare , CleanBrowsing , OpenDNS , NextDNS , Google DNS)]

-

On Privacy Menu :

Add HTTPS Everywhere Toggle Switch [On/Off]
(Like in the HTTPS Everywhere Extension)

**Comment by Ultimatinium** [comment]
I forgot to write...

On The Privacy Menu :
> Add Broadcast IP (WebRTC Performance) Toggle Switch [On/Off]

**Comment by jamal2362** [comment]
Currently there is no change in this regard for other reasons.
