### ISSUE TITLE
Reader Mod

### ISSUE THREAD

**Issue by bakinazik** [jamal2362/Styx#59]
**Describe the bug**
Reader mode background is not black even though I am in Amoled design. It also produces error warnings as seen in the images and strange when changing between dark/light theme

**Screenshots**
![image](https://user-images.githubusercontent.com/61169988/123525236-dbddf000-d6d7-11eb-8012-750d5448a40a.png)
![image](https://user-images.githubusercontent.com/61169988/123525240-e13b3a80-d6d7-11eb-8284-efea12a69c01.png)

**Smartphone (please complete the following information):**
 - Device: [Honor 9 Lite]
 - OS: [Android 9]
 - Browser [e.g. Styx Browser]
 - Version [e.g. 13.0]

**Comment by jamal2362** [comment]
Hi,

I can not reproduce this error with my 3 devices.

Do you have special settings enabled in Styx?

Have you looked in the system settings of Huawei whether he Force dark mode for Styx is disabled ?

**Comment by bakinazik** [comment]
I delete and reinstall the app. I am facing the same issue when I turn on reader mode with default settings.

**Comment by bakinazik** [comment]
i think the problem occurs on some versions of phones with arm processor
