### ISSUE TITLE
Dark mode not working when SDK is set to 33

### ISSUE THREAD

**Issue by R0M4N0F5K7** [jamal2362/Styx#6]
First of all: Welcome back, so glad to see styx being public again.

Sadly dark mode doesn't seem to work at all in the new version on my phone (pixel 4a running calyxOS).

Neither the "Dark Mode" checkbox in the menu nor the "Force dark mode" setting seem to have any effect.

**Comment by jamal2362** [comment]
Yes this is a issue when you using Android 13.

I will try to fix it for newer Android versions.
