### ISSUE TITLE
Hide tool bar when scrolling down improvement

### ISSUE THREAD

**Issue by tsiflimagas** [jamal2362/Styx#60]
**Describe the bug**

'hide tool bar when scrolling down' doesn't work that good currently regarding showing the tool bar back. It seems that the feature has to do with the velocity of the scroll gesture, thus if it's not fast enough, it's not triggered. You can do long scrolls up and slowly and tool bar won't appear. Also, you have to scroll up and release, if keep your finger longer and then release, tool bar doesn't show either. For scroll down it's pretty much ok though.
I think it would be optimal if this worked like it does in Firefox. The moment you move your finger up or down, tool bar starts to move accordingly.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 8
 - OS: Android 11
 - Browser: Styx Browser
 - Version: 15.0

**Comment by Slion** [comment]
@tsiflimagas Thanks for using a Web Browser based on [Fulguris](https://github.com/Slion/Fulguris).
Our 'Show toolbar when scrolling up' feature was designed that way. The intention is to still allow scrolling up a bit without having the toolbar showing. I'm not sure if this was changed in Styx but in Fulguris you can show the toolbar anytime by using your device Back action, gesture or button.
It's also worth noting that this option is not enabled by default in Fulguris, again this may have been changed in Styx.
In fact Fulguris' defaults to not hidding toolbar in landscape cause you have plenty of vertical screen real estate and agressive toolbar hidding in landscape cause vertical screen real estate is precious then.

**Comment by jamal2362** [comment]
@Slion 
It is 99% identical to Fulguris.
Except that on Special URL pages like the homepage the toolbar cannot be hidden.

**Comment by jamal2362** [comment]
But when I look at all the Lightning Based browsers, SmartCookieWeb has implemented this the best. It works the best according to my tests.

**Comment by Slion** [comment]
@jamal2362 I see, you did simplify those settings a bit.
@tsiflimagas That means in Styx you can't hide when scrolling down without not showing when scrolling up. Ho well, details anyway. On Styx doing the Back action will open the toolbar for you or just quick scroll up will do it too.

**Comment by Slion** [comment]
@tsiflimagas For the reasons explained in my first post I'm not planning to change the current implementation for the time being. Yes it does differ from why you find on mainstream browsers so it can take some time to get used to it. However there is actually some reasoning behind it.

**Comment by Slion** [comment]
> But when I look at all the Lightning Based browsers, SmartCookieWeb has implemented this the best. It works the best according to my tests.
> 
> Here can you see the difference between SmartCookieWeb and Fulguris.
> 
> https://streamable.com/mc4u2q

Except that I believe SmartCookieWeb still has that WebView overflow issue. Meaning when it shows the toolbar the bottom of the WebView is outside the screen.
