### ISSUE TITLE
Dark Mode on webpages following System Theme/Styx's Theme

### ISSUE THREAD

**Issue by MrigendraB** [jamal2362/Styx#65]
Please add an option to make dark mode on webpages follow system's theme.
It would be helpful for people using Styx in dark which would save people from getting a white flash at launch.
Thanks!

**Comment by Slion** [comment]
Thanks for using a Web Browser based on [Fulguris](https://github.com/Slion/Fulguris). I believe the white screen flash on start-up is a regression introduced in Styx.
Setting your theme to Default should follow system theme.
I'm not sure using force dark mode when theme is set to dark is practical.
