### ISSUE TITLE
TTS doesn't work on some devices

### ISSUE THREAD

**Issue by ZaOrujin** [jamal2362/Styx#71]
As the title,the tts fuction didn't work on my phone.When I press the button,it has an error in log: `E TTS     : Initilization Failed` and nothing else happened. I can use other tts apps normally. I guess its due to [this](https://developer.android.com/about/versions/11/behavior-changes-11#accessibility) and I did'n find a such line in this app's manifist. Thank you for your wonderful app!(and sorry for my bad English)

**Comment by jamal2362** [comment]
@ZaOrujin 

Thank you for the message.

Can you send me a detailed log?

**Comment by ZaOrujin** [comment]
`08-24 16:14:15.408  4864  4864 E TTS     : Initilization Failed                                                       08-24 16:14:15.574  4864  4864 W TextToSpeech: isSpeaking failed: not bound to TTS engine                             08-24 16:14:15.702  4864  8698 W System  : A resource failed to call release.                                         08-24 16:14:16.814  4864  4864 W TextToSpeech: isSpeaking failed: not bound to TTS engine                             08-24 16:14:16.814  4864  4864 W TextToSpeech: speak failed: not bound to TTS engine                                  08-24 16:14:16.829  4864  4864 W TextToSpeech: isSpeaking failed: not bound to TTS engine                             08-24 16:14:18.807  4864  4864 W TextToSpeech: stop failed: not bound to TTS engine`

**Comment by jamal2362** [comment]
Thank you!
I will look in to this issue.

One more question:
What kind of device is it ?
