### ISSUE TITLE
Include attributation to upstream project in README

### ISSUE THREAD

**Issue by FruityWelsh** [jamal2362/Styx#73]
From my understanding, the project [Fulguris](https://github.com/Slion/Fulguris/commits?author=anthonycr) is used as an upstream to this project, and updates from this project actively make their way down to this one.

Would there be any issue with including an attribution to this project into the README in order to honor the work that has helped to improve this project?

**Comment by jamal2362** [comment]
There is no such thing in the readme.
You can find the acknowledgement in the app in the settings.

**Comment by jamal2362** [comment]
![Screenshot_20210817-184106](https://user-images.githubusercontent.com/15986930/129766287-082860a8-83f2-4676-a03d-39d754112eb0.jpg)

**Comment by Slion** [comment]
In the future to make sure Fulguris benefits from the success of rebranding efforts, rebrand will be asked to link to and credit Fulguris on every application update by showing a pop-up saying something like:

> Styx is based on Fulguris. Make sure your support Fulguris so that Styx can benefit from it.

**Comment by Slion** [comment]
See: https://github.com/jamal2362/Styx/issues/75
