### ISSUE TITLE
Credit Fulguris on every update

### ISSUE THREAD

**Issue by Slion** [jamal2362/Styx#75]
In the future to make sure Fulguris benefits from the success of rebranding efforts, rebrand will be asked to link to and credit Fulguris on every application update by showing a pop-up saying something like:

> Styx is based on Fulguris. Make sure you support Fulguris so that Styx can benefit from it.

**Comment by jamal2362** [comment]
This is not planned so far and will not add this. Except here in the readme on GitHub. That should be enough.

In your readme on GitHub, the entry for Lighning Browser is also missing. With you this is also not present.

**Comment by jamal2362** [comment]
@Slion added the missed Licence and Credit on GitHub with this commit.
https://github.com/jamal2362/Styx/commit/d187393acbc47520398230e2cfe8335220b8f9a4

https://github.com/jamal2362/Styx/commit/bc17e6c5904ce1690b202a268cd72c8d08b82f67
