### ISSUE TITLE
Improved scoll behaviour

### ISSUE THREAD

**Issue by leonp5** [jamal2362/Styx#76]
**Description**
The scroll behaviour could be more smooth. It could be easier to skip longer sections of a page by "fast" scrolling.
It keeps a while until you figure out, how to swipe over the display for a scroll behaviour that **doesn't** stop immediately after you release the finger.

**Solution**
If you scroll and accelerate the scrolling and then release the finger the page should scroll further for a while.

**Comment by jamal2362** [comment]
Hey,

This is not planned in the Future.

I will not change anything in the behavior, it remains the scroll function of the system.
