### ISSUE TITLE
When using hide toolbar, it requires to much action to make it re-appear

### ISSUE THREAD

**Issue by R0M4N0F5K7** [jamal2362/Styx#8]
When using "Hide tool bar when scrolling down" it is rather particular about the swift and fast swipe downwards it requires to make the tool bar re-appear.

It is not at all picky about making it disappear in the first place, any swipe at any speed upwards seems to make it disappear as soon is I let go after the upwards swipe.

(Generally speaking it feels a bit weird to me that I have to lift my finger after swiping for it to take effect on the toolbar. When slowly reading something and scroll down I might just stop and move half a centimeter in the other direction to check the url or how many taps I have open and then continue reading, slowly scrolling further down - all without ever letting go of the screen.
This is the behaviour I have in other mobile browser like firefox.)

That might sounds picky and I think it's fine if it continues to only take an effect on the display value after letting go, but still - the effort/action it requires for the bar to reappear is too much, especially in comparison to what it takes for it to disappear. It shouldn't require a swipe that makes me loose my place on the page in order to access the tool bar and menu.

**Comment by jamal2362** [comment]
Hey!
Currently there is no change planned there.
If I decide to change this, I will reopen this issue.
