### ISSUE TITLE
Home page default does not change from Google despite attempts

### ISSUE THREAD

**Issue by AlanSmythe** [jamal2362/Styx#8]
Hello,

I like to support new, non-chromium browsers and I think this one has potential. However in trying to use it there has been one thing that has bothered me. I try to set it so that my home page is duckduckgo. However despite that, it will always default to a homepage that looks like Google. Only by hitting refresh will it then take me to what website I actually set as my homepage.

Is there anyway to make it so the browser will actually start up with my chosen website?

**Comment by jamal2362** [comment]
Hello @AlanSmythe ,
Have you tried this as in the pictures ?

![Screenshot_20210426-164312](https://user-images.githubusercontent.com/15986930/116102430-ffbc8f80-a6ae-11eb-9d51-05535eba705f.jpg)

![Screenshot_20210426-164335](https://user-images.githubusercontent.com/15986930/116102447-03501680-a6af-11eb-9a09-ace5234743df.jpg)

![Screenshot_20210426-164401](https://user-images.githubusercontent.com/15986930/116102463-06e39d80-a6af-11eb-84d1-bb792d16db0a.jpg)

**Comment by AlanSmythe** [comment]
Setting the search engine wasn't the setting I was referring to, what I was referring to was setting a custom home page. However, upon testing the browser again today it appears to be working. Last night it would start up to google first and then when I hit refresh it would take me my custom homepage (start.duckduckgo, not the normal duckduckgo I should have said.) 

Since it appears to be working now, I will close this issue.

**Comment by jamal2362** [comment]
All right thanks for the reporting.
I will have a closer look in this issue :)
