### ISSUE TITLE
Homapage UI Changes

### ISSUE THREAD

**Issue by sahabuddinsk** [jamal2362/Styx#80]
Can you Change Homepage UI to https://play.google.com/store/apps/details?id=net.fast.web.browser this web browser type. 

Your Homepage is all ok. but littlie bit changes.

only middle section search box with show search engine icon, user can change search engine through icon click.
then show bookmarks with icon also add bookmarks link with pop-up. already your application has in right drawer.

This simple UI Can you please change. then it will be look perfectly.

**Comment by jamal2362** [comment]
No Changes at the Moment.
