### ISSUE TITLE
Is TTS implemented yet? I can't seem to find it.

### ISSUE THREAD

**Issue by bet** [jamal2362/Styx#9]
I don't see any option  or setting, mentioning it, and while there's a likely looking icon in to top right corner of reader mode, it doesn't seem to do anything. I'm on a Google Pixel 3, fully updated, stock OS.

**Comment by jamal2362** [comment]
What language do you have set on your device ?
Not all languages are supported for the TTS function.

Info:
The TTS function does not work on all pages.

**Comment by bet** [comment]
When I go to Settings / System / Languages & Input

it says English (United States)

and TTS works fine in ereader apps like Cool Reader, and using TTS Util from f-droid. I tried testing it by asking Styx to read me the text from a plain text file I visited on my website, my resume:

https://bet.github.io/resume/resume.txt

where is the control to engage TTS? Is it the little graphic at the top right corner in Reader Mode? When I touch that, it pops up a text box saying Read Page, but nothing happens

**Comment by bet** [comment]
sorry, correction, when I long press (not "touch" the icon, the popup box says "Read page" with a lowercase "p".

And, thank you for your time and attention.

**Comment by jamal2362** [comment]
As I said on some pages reading a text aloud does not work.

Some pages work fine with TTS and other pages do not.

Go to google.com and see if TTS works there.
Unfortunately some pages do not work, I have no influence on it.

Sorry :/

**Comment by bet** [comment]
You solved it! My test page was the problem. google.com works fine.

It never occurred to me that a plain txt file would fail when a complex web page would work.

Sorry for bothering you, and thanks for finding my (self-inflicted) problem.

**Comment by jamal2362** [comment]
No problem.
I'm here to help.

If I find a solution, then I will write it here.

Thanks for the message and see you :)
