### ISSUE TITLE
Custom added blocklists won't backed up

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#92]
**Describe the bug**

I added two more blocklists to adblocker and many other customizations, then backed them up (with backup settings option) and then i imported the backup file to another device and saw that those blocklists didn't imported.

I don't know if this problem is related to import or backup.

But it was always like this.

Custom blocklists won't get backed up seems.
Backed up file:

Android pie
Styx 15.4

Imported devices:

Android pie
Android oreo

All with styx 15.4 installed.

**Comment by jamal2362** [comment]
Blocklists are not saved when you backup the settings. 
You will lose them when you do a fresh install.
The blocklists would have to be re-added manually.

The option backup settings really only refer to the selected things you do, but with the adblocker this option has nothing to do.

**Comment by rustforfuture** [comment]
Even remote blocklists added?

Oh, I See.
Thank you
