### ISSUE TITLE
[UX][Accessibility/Usability] Please increase limit of text size option to 300 percent or more

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#93]
**Is your feature request related to a problem? Please describe.**

I use Styx in an unknown brand android box in TV because my eyes can't tolerate screens that are close to me.

I have dry eye syndrome, pain and other problems that didn't become better after nore than one year of treatment and even i must use eye ointment so that i can even see TV for limited time.

**Describe the solution you'd like**

Please let us increase text size to more than current maximum value.

300 or more will be great.

Thank you

**Describe alternatives you've considered**

Please also let us increase text size more in reader mode also for articles

although some Q/A websites like stackexchange, Quora, Forums and such needs that the limit uplifted in main browser also.

**Additional context**

Nothing probably

**Comment by jamal2362** [comment]
I will include this improvement. I will increase the text size up to 400%. Currently this is only possible up to 250%.

**Comment by jamal2362** [comment]
The improvement is now implemented.

**Comment by rustforfuture** [comment]
Really Thank you.
Thank you very much
