### ISSUE TITLE
Please add an option to open that webpage in another app/browser like the option in three dot menu of smartcookieweb

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#95]
**Is your feature request related to a problem? Please describe.**

Please add an option to open that webpage in another app/browser like the option in three dot menu of smartcookieweb

**Describe the solution you'd like**

Also please let us disable all "do you need to open this page in another app?" prompts because if you add that option, then there is no need for this.

You can check "handling all clicked links in Smartcookieweb" option in Smartcookieweb settings for this.

**Describe alternatives you've considered**

**Additional context**

Thank you very much

**Comment by jamal2362** [comment]
Do you mean a share function ?
So the sharing of URL addresses ?

**Comment by rustforfuture** [comment]
No, i mean this:

![IMG_20211104_193339_419](https://user-images.githubusercontent.com/49192003/140399470-0f0eeb15-45ad-4b25-a835-72bf6a3eb88f.jpg)

**Comment by jamal2362** [comment]
Thank you for the screenshot i will look in to this feature :)

**Comment by jamal2362** [comment]
The improvement is now implemented.

**Comment by rustforfuture** [comment]
Thank you very much.
You are fastest dveloper i have ever seen😃😍❤️

**Comment by rustforfuture** [comment]
Thank you very much.
You are fastest dveloper i have ever seen😃😍❤️

Really Thank you for all of your efforts.

**Comment by rustforfuture** [comment]
Hello

May i know why you reverted open in an app/browser option?

Thanks

**Comment by jamal2362** [comment]
I took another look at this feature. This function does not work for every website although the app is installed on the system. Also, you get a pop-up notification when a matching app is found.

Therefore, I have removed this again for the time being.
I hope I have not annoyed you with it. Sorry that I had to take this out again.

**Comment by rustforfuture** [comment]
Oh, I See.
Thank you.
I was thinking that this option that you added + https://github.com/Slion/Fulguris/issues/262 will be a good way to make this prompts manuall.

That way the behavior would become like Firefox for android that let user prevent browser prompting opening in app but have an option so when user wants, open that page manually in that app.

And this option also worked for someone like me that use several browsers (one with JS disabled and one with JS enabled)

But the choice is yours.
By the way thank you very much.
Best wishes.
