### ISSUE TITLE
Please add an option to three dot menu to copy page URL in clipboard

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#96]
**Is your feature request related to a problem? Please describe.**

Please add an option to three dot menu to copy page URL in clipboard

Like lightning and smartcookieweb.

It will be great although currently browser has share this page option, it also has good use cases.

**Additional context**

Thank you very much

**Comment by jamal2362** [comment]
Good idea.
I'm thinking about adding this but copying the URL is possible via the address bar.

**Comment by rustforfuture** [comment]
Thank you very much

Yes, but for some use cases it will sace time.

For example, when we want archive a webpage in archive.is or archive org/web or such websites.

Or seeing an archived version in such websites.

**Comment by jamal2362** [comment]
The improvement is now implemented.

**Comment by rustforfuture** [comment]
Thank you very much 🌹
