### ISSUE TITLE
[Feature] [UX] [Accessibility/Usability] May you please let us to change the behavior of one tap on a link?

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#97]
Hello

May you please let us to change the action of one tap on a link 

So we can set it to open that link in background instead of current behavior of it?

---------

### Some Background info and use case

My request is if may please add an option and when we enable it, then when we tap on a link in a webpage, Styx open it in the background instead of opening it in same tab (that is current behavior of Styx)

---------

If you implement this option, it will be a real life saver for those of us that always use open in the background option

So we don't need to tap and hold every link and then tap "open in background"

It also makes using Styx very easy with mouse.

Thank you very much
Best wishes for you
Stay safe, stay healthy

**Comment by rustforfuture** [comment]
I updated my request with a clear and short explanation

Best regards.

**Comment by jamal2362** [comment]
Hello currently there is no change planned.
I am sorry.
Therefore I close here.
