### ISSUE TITLE
May you consider adding the app to main repo of F-Droid when conflicts ended?

### ISSUE THREAD

**Issue by rustforfuture** [jamal2362/Styx#98]
May you consider adding the app yo main repo of F-Droid when conflicts ended?

It will be great.

Thank you very much

**Comment by jamal2362** [comment]
I think no.
Styx is already present on IzzyOnDroid and I'll leave it that way for now.

**Comment by rustforfuture** [comment]
Oh, I See.
OK.
Thank you
