### ISSUE TITLE
Add "Powered by Fulguris" notice on application start-up after update.

### ISSUE THREAD

**Issue by jamal2362** [jamal2362/Styx#99]
I will include a "Powered by Fulguris" notice when launching the app after the update soon in the app.

This message comes after every app update from Styx.
@Slion and I have agreed to do this.

**Comment by jamal2362** [comment]
@Slion

![Screenshot_1636132624](https://user-images.githubusercontent.com/15986930/140551969-9c3ba002-0a4d-401b-a55c-1005893c0d70.png)
![Screenshot_1636132655](https://user-images.githubusercontent.com/15986930/140551973-099e41b4-7edd-49e7-b005-e8ccdf4a4da2.png)

**Comment by Slion** [comment]
Thanks for working on this. We want to make sure the "Powered by Fulguris" is not too much in the user's face though. I was thinking when the app starts maybe just use a Snackbar to display only the words "Powered by Fulguris" maybe make the word Fulguris the clickable action, or maybe the click action should be the whole "Powered by Fulguris", yeah that second option is probably better.
When there is an update from the Fulguris code base then using a dialog that includes "Powered by Fulguris" is a good idea but you should not ask "Do you want to redirected to Fulguris" that's too much. Ideally "Powered by Fulguris" should be clickable and links to http://fulguris.slions.net but not the main subject of the dialog.

Yes the want to credit to be there and visible enough but we also don't want it to turn down the users so finding the right balance is important.

Hope that makes sense.

**Comment by jamal2362** [comment]
@Slion 

Thanks for the answer.
I have rebuilt this according to your wishes.
Namely, this snackbar comes after each update of Styx and when you install the app on first start.
If you click on "Open" then you will be redirected to the slions.net website.
Is this so ok now?

![Screenshot](https://user-images.githubusercontent.com/15986930/140610122-68319346-6ba5-4505-8c79-eb51c4c1a9d9.png)

**Comment by Slion** [comment]
Instead of "Open" just put: Powered by ⚡Fulguris
As for the white text, maybe try not putting any text.
I'm not sure we should translate Powered by ⚡Fulguris maybe it should remain like that for every language.

**Comment by jamal2362** [comment]
So better ?
![Screenshot_1](https://user-images.githubusercontent.com/15986930/140612654-b1b9ea26-850b-45ff-8a1b-b04b8e820e6a.png)

**Comment by Slion** [comment]
Perfect, I approve!

**Comment by jamal2362** [comment]
Perfect!
I have merged the changes.
I close this issue now. 😎
